#!/usr/bin/env python3
"""Create a clean agent workspace and install one FreeCAD macro wrapper."""

import argparse
import os
import platform
from pathlib import Path


ROOT = Path(__file__).resolve().parent
MACRO_SOURCE = ROOT / "freecad_folder_watch_agent.FCMacro"
WORKSPACE_FILES = [
    "freecad_folder_watch_agent.FCMacro",
    "agent_submit.py",
    "agent_data.py",
    "AGENTS.md",
    "README.md",
]
WORKSPACE_DIRS = ["models", "inbox", "out", "logs"]
WORKSPACE_LINK_DIRS = ["examples"]
DEFAULT_MACRO_NAME = "freecad_agent.FCMacro"
OLD_MACRO_NAME = "freecad_folder_watch_agent.FCMacro"


def default_freecad_macro_dir():
    system = platform.system()
    if system == "Darwin":
        return Path.home() / "Library" / "Application Support" / "FreeCAD" / "Macro"
    if system == "Windows":
        app_data = os.environ.get("APPDATA")
        if app_data:
            return Path(app_data) / "FreeCAD" / "Macro"
    return Path.home() / ".local" / "share" / "FreeCAD" / "Macro"


def default_workspace():
    return Path.home() / "FreeCADAgent"


def parse_args():
    parser = argparse.ArgumentParser(
        description="Set up the FreeCAD folder-watch agent workspace."
    )
    parser.add_argument(
        "--workspace",
        default=os.environ.get("FREECAD_AGENT_WORKSPACE", str(default_workspace())),
        help="Clean working directory used by agents. Defaults to ~/FreeCADAgent.",
    )
    parser.add_argument(
        "--freecad-macro-dir",
        default=str(default_freecad_macro_dir()),
        help="FreeCAD user macro folder.",
    )
    parser.add_argument(
        "--macro-name",
        default=DEFAULT_MACRO_NAME,
        help="Name of the single generated FreeCAD macro.",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Replace files previously generated by this installer.",
    )
    return parser.parse_args()


def ensure_source_files():
    missing = [name for name in WORKSPACE_FILES if not (ROOT / name).exists()]
    missing.extend(name for name in WORKSPACE_LINK_DIRS if not (ROOT / name).exists())
    if missing:
        raise SystemExit("Missing source files: {}".format(", ".join(sorted(missing))))


def link_or_replace(source, target, force=False):
    if target.is_symlink():
        try:
            if target.resolve() == source.resolve():
                return
        except OSError:
            pass
        if force:
            target.unlink()
        else:
            raise SystemExit(
                "Refusing to replace existing symlink: {}\n"
                "Re-run with --force if this was generated by this installer.".format(target)
            )
    elif target.exists():
        raise SystemExit(
            "Refusing to overwrite existing path: {}\n"
            "Move it away or choose another --workspace.".format(target)
        )

    target.parent.mkdir(parents=True, exist_ok=True)
    target.symlink_to(source)


def write_text_or_replace(path, content, force=False):
    generated_marker = "Generated by FreeCAD Folder Watch Python Agent"
    if path.exists() or path.is_symlink():
        if path.is_symlink():
            if force:
                path.unlink()
            else:
                raise SystemExit(
                    "Refusing to replace existing symlink: {}\n"
                    "Re-run with --force if this was generated by this installer.".format(path)
                )
        else:
            existing = path.read_text(encoding="utf-8", errors="replace")
            if generated_marker not in existing and not force:
                raise SystemExit(
                    "Refusing to overwrite existing file: {}\n"
                    "Re-run with --force if this was generated by this installer.".format(path)
                )
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def workspace_gitignore():
    return """# Generated by FreeCAD Folder Watch Python Agent.
inbox/*
!inbox/.gitkeep
out/*
!out/.gitkeep
logs/
models/
"""


def macro_wrapper(workspace, macro_path):
    return """# Generated by FreeCAD Folder Watch Python Agent.
# Run this macro in FreeCAD. Re-run it after bridge code changes.
import os
from pathlib import Path

os.environ["FREECAD_AGENT_ROOT"] = {workspace!r}
macro_path = Path({macro_path!r})
exec(compile(macro_path.read_text(encoding="utf-8"), str(macro_path), "exec"))
""".format(
        workspace=str(workspace),
        macro_path=str(macro_path),
    )


def ensure_keep_file(directory):
    keep = directory / ".gitkeep"
    if not keep.exists():
        keep.write_text("", encoding="utf-8")


def create_workspace(workspace, force=False):
    workspace.mkdir(parents=True, exist_ok=True)

    for name in WORKSPACE_FILES:
        link_or_replace(ROOT / name, workspace / name, force=force)

    for name in WORKSPACE_LINK_DIRS:
        link_or_replace(ROOT / name, workspace / name, force=force)

    for name in WORKSPACE_DIRS:
        directory = workspace / name
        directory.mkdir(parents=True, exist_ok=True)
        if name in ("inbox", "out"):
            ensure_keep_file(directory)

    write_text_or_replace(workspace / ".gitignore", workspace_gitignore(), force=force)


def remove_old_generated_macro(macro_dir, source):
    old_target = macro_dir / OLD_MACRO_NAME
    if old_target.is_symlink():
        try:
            if old_target.resolve() == source.resolve():
                old_target.unlink()
        except OSError:
            pass


def install_macro_wrapper(workspace, macro_dir, macro_name, force=False):
    macro_dir.mkdir(parents=True, exist_ok=True)
    workspace_macro = workspace / "freecad_folder_watch_agent.FCMacro"
    remove_old_generated_macro(macro_dir, workspace_macro)
    remove_old_generated_macro(macro_dir, MACRO_SOURCE)

    target = macro_dir / macro_name
    write_text_or_replace(
        target,
        macro_wrapper(workspace.resolve(), workspace_macro),
        force=force,
    )
    return target


def main():
    args = parse_args()
    ensure_source_files()

    workspace = Path(args.workspace).expanduser().resolve()
    macro_dir = Path(args.freecad_macro_dir).expanduser().resolve()

    create_workspace(workspace, force=args.force)
    macro_target = install_macro_wrapper(
        workspace,
        macro_dir,
        args.macro_name,
        force=args.force,
    )

    print("workspace: {}".format(workspace))
    print("freecad macro: {}".format(macro_target))
    print("")
    print("Open FreeCAD and run:")
    print("Macro > Macros... > {} > Execute".format(macro_target.name))
    print("")
    print("Agents should work from:")
    print(workspace)


if __name__ == "__main__":
    main()
